---
title: "Spatial Sampling, then OLS"
output: html_document
---

1. Sample cells at 100km distance to skip spatial autocorrelation
2. Regular OLS
3. Model evaluation.
4. Repeat above for consistency

## read data

```{r}

library(ggplot2)
library(tidyverse)
library(broom)
library(dplyr)
library(rgdal)
library(rgeos)
library(raster)
library(sf)
library(sp)
library(tmap)
library(viridis)
library(spdep)
library(spatialreg)
library(lmtest)
library(Metrics) # for rmse
library(leaflet)
library(leaps) # stepwise model selection

#E:/R-code/Modeling/code/FCN_clean_csvs.R
#~/Documents/R-code
source('E:/R-code/Modeling/code/FCN_clean_csvs.R')
source('E:/R-code/Modeling/code/FCN_plotting.R')
source('E:/R-code/Modeling/code/FCN_sample_data.R')
source('E:/R-code/Modeling/code/FCN_run_model_spatial_sampled.R')

MT_outline <- readOGR(dsn = 'E:/R-code/Modeling/data/shp/MatoGrossoOutline', layer = 'MatoGrossoOutline')
crs(MT_outline) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

median_cell_raw <- read.csv('E:/R-code/Modeling/data/median_onset_cell_v2.csv')

grid_1deg <- readOGR(dsn = 'E:/R-code/Modeling/data/shp/grid_1deg', layer = 'grid_1deg')
munis <- readOGR(dsn = 'E:/R-code/Modeling/data/shp/munis', layer = 'munis_SHP')
crs(munis) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")
  
cell_sf <- st_read(dsn = 'E:/R-code/Modeling/data/shp/median_onset_cell', layer = 'median_onset_cell_SHP')

min_soy_area <- 2 #km2. min area of total or SC/DC soy in cell, muni or property to be considered in model

```

## read and clean spatial data

```{r}

# CSV DATA -----------------------------------------------------------------------------------------------------------------
# median cell
median_cell <- median_cell_raw %>% delete_cols_median_cell() %>%
                                    rename_cols_median_cell()

# SF DATA ------------------------------------------------------------------------------------------------

cell_sf$cell_ID <- median_cell$cell_ID
cell_sf$cell_ID <- sapply(as.character(cell_sf$cell_ID), clean_cell_ID)


cell_sf_tidy <- cell_sf %>% tidy_by_intensity_plant("SC_plant", "DC_plant") %>%
            #tidy_by_intensity_delay("SC_delay", "DC_delay") %>%
            dplyr::select(-c(SC_harvest, DC_harvest)) %>%
            categorize_regions_cell_sf_tidy() # categorize cells into four regions


cell_sf_tidy$year_index <- cell_sf_tidy$year - 2003
cell_sf_tidy$year_factor <- as.factor(cell_sf_tidy$year)

cell_sf_tidy <- cell_sf_tidy %>%  drop_na

```


## functions to evaluate different sampling strategies and predictors

```{r}

run_OLS <- function(full_data, predictors, y.var,
                    grid_size, lat_offset, lon_offset, agg_scheme, 
                    plot_samples, plot_model_evals, year_oi, do_elim_year) {
  
  # get sampled data
  sampled_data <- get_sampled_data(full_data = cell_sf_tidy, grid_size = grid_size, 
                                   lat_offset = lat_offset, lon_offset = lon_offset, agg_scheme = agg_scheme, 
                                   plot_samples = plot_samples, year_oi = year_oi)
  
  
  # map of the input data used (for specific year and intensity)
  if (plot_samples) {
    print(plot_cell_onset(year_oi, sampled_data))
    print(plot_cell_plant(year_oi, sampled_data, "DC"))
  }

  # define the formula
  formula.string <- paste(y.var, paste(predictors, collapse = " + "), sep = " ~ ")
  
  f <- as.formula(formula.string)

  # do the model
  
  model = lm(f, data=sampled_data) 
  sampled_data$residuals <- residuals(model)
  sampled_data$fitted.values <- fitted.values(model)
  
  # map of residuals
  if (plot_model_evals) {print(plot_cell_residuals(year_oi, sampled_data, "DC"))}
  
  # evaluation
  
  # 1. coefficients and their p values
  coefficients <- model$coefficients
  onset_coef <- coefficients["onset"]
  intensity_coef <- coefficients["intensitySC"]
  #lat_coef <- coefficients["lat"]
  
  p_vals <- summary(model)$coefficients[, ncol(summary(model)$coefficients)]
  onset_pval <- p_vals["onset"]
  intensity_pval <- p_vals["intensitySC"]
  #lat_pval <- p_vals["lat"]
  
  # 2. percent data used
  percent_data_used <- 100*nrow(sampled_data)/nrow(full_data)
  
  # 3. R2
  SST <- sum((sampled_data$plant - mean(sampled_data$plant))^2)
  SSE <- sum((sampled_data$residuals - mean(sampled_data$residuals))^2)
  R2 <- 1 - SSE/SST
  
  # 4. exogeneity plots (residual vs predictors)
  if (plot_model_evals) {
    plot(sampled_data$onset, sampled_data$residuals, main = "onset vs residual (exogeneity)")
    #plot(sampled_data$lat, sampled_data$residuals, main = "latitude vs residual (exogeneity)")

    plot(sampled_data$year, sampled_data$residuals, main = "year vs residual (exogeneity)") 
    abline(h = 0)
  }
  
  # 5. spatial autocorrelation
  
  # need 'one layer': one year, one intensity, set up weights
  to_autocorrelation <- sampled_data[sampled_data$year == year_oi & sampled_data$intensity == "DC", ]
  to_autocorrelation_sp <- as(to_autocorrelation, "Spatial")
  st_geometry(to_autocorrelation) <- NULL # turn to_autocorrelation into data frame
  centroids <- coordinates(to_autocorrelation_sp)
  to_autocorrelation_points <- SpatialPointsDataFrame(coords = centroids, data = to_autocorrelation)
  nb<-knn2nb(knearneigh(to_autocorrelation_points)) 
  lw <- nb2listw(nb, zero.policy = TRUE)
  
  # calculate spatial autocorrelation
  moran_residual <- moran.mc(to_autocorrelation_points$residuals, lw, 500, zero.policy = TRUE)
  moran_onset <- moran.mc(to_autocorrelation_points$onset, lw, 500, zero.policy = TRUE)
  moran_plant <- moran.mc(to_autocorrelation_points$plant, lw, 500, zero.policy = TRUE)
  
  residual_moran <- moran_residual$statistic
  residual_moran_pval <- moran_residual$p.value
  onset_moran <- moran_onset$statistic
  onset_moran_pval <- moran_onset$p.value
  plant_moran <- moran_plant$statistic
  plant_moran_pval <- moran_plant$p.value
  
  # 6. residual plots (homoscedasticity, normality of error, residual-fitted value correlation)
  if (plot_model_evals) {
    test_plots(model, paste("grid size", grid_size, "lat offset", lat_offset, 
                            "lon_offset", lon_offset, "aggregated", agg_scheme))
    plot(sampled_data$plant, sampled_data$fitted.values, 
         main = "fitted value vs actual value of plant", ylab = "fitted.values")
    abline(h = mean(sampled_data$fitted.values), col = "blue")
    abline(v = mean(sampled_data$plant), col = "blue")
    abline(0,1, col = "gray", lwd = 3)
  }
  
  # 7. multicollinearity: look at max absolute correlation between predictors
  predictors <- sampled_data[,c("onset", "year")]
  st_geometry(predictors) <- NULL
  correlations <- cor(predictors)
  diag(correlations) <- 0 # place 1 with 0 on diagonal
  highest_predictor_correlation <- max(abs(correlations))

  
  # 8. predictive ability, when eliminate one year
  
  if (do_elim_year) { # set do_elim_year to FALSE if using year as fixed effect
    prediction_results_elimyear <- data.frame()
  
    for (year in 2004:2014) {
      
      result <- run_model_for_prediction_elimyear(sampled_data, year, TRUE, f)
      prediction_results_elimyear <- rbind(prediction_results_elimyear, result)
    }
    
    names(prediction_results_elimyear) <- names(result)
    
    if (plot_model_evals) {
      plot(prediction_results_elimyear$eliminated_year, prediction_results_elimyear$RMSE, 
           ylab = "RMSE", xlab = "eliminated year", ylim = c(5, 25), type = "l", 
           main = "Prediction RMSE, spatial sampling")
      
      
      # plot(prediction_results_elimyear$eliminated_year, prediction_results_elimyear$RMSE_improvement, 
      #      ylab = "RMSE", xlab = "eliminated year", ylim = c(0, 10), type = "l", 
      #      main = "Prediction RMSE improvement over intercept, spatial sampling")
      
      # plot(prediction_results_elimyear$eliminated_year, prediction_results_elimyear$onset, type = "l", col = "red", 
      #      ylab = "coef or R2", xlab = "eliminated year", ylim = c(0.1, 0.7), 
      #      main = "Prediction onset and R2, spatial sampling")
      # lines(prediction_results_elimyear$eliminated_year, prediction_results_elimyear$R2, col = "blue")
      # legend(2004, 0.65, legend = c("onset coef", "R2"), col = c("red", "blue"), lty= c(1,1))
    }
  }
  
  # 9. predictive ability, location cross validation
  
  prediction_results_elimlocation <- run_model_for_prediction_elimlocation(full_data = sampled_data,
                                      formula = f,
                                      year_for_location = 2004, year_oi = 2011,
                                      plot_model_evals = plot_model_evals)
  
  if (do_elim_year) {
    output_list <- list(onset_coef = onset_coef, 
                      intensity_coef = intensity_coef,
                      #lat_coef = lat_coef,
                      onset_pval = onset_pval,
                      intensity_pval = intensity_pval,
                      #lat_pval = lat_pval,
                      percent_data_used = percent_data_used,
                      R2 = R2,
                      residual_moran = residual_moran,
                      residual_moran_pval = residual_moran_pval,
                      onset_moran = onset_moran,
                      onset_moran_pval = onset_moran_pval,
                      plant_moran = plant_moran,
                      plant_moran_pval = plant_moran_pval,
                      highest_predictor_correlation = highest_predictor_correlation,
                      prediction_results_elimyear = prediction_results_elimyear,
                      prediction_results_elimlocation = prediction_results_elimlocation
                      )
  }
  
  if (!do_elim_year) {
    output_list <- list(onset_coef = onset_coef, 
                      intensity_coef = intensity_coef,
                      #lat_coef = lat_coef,
                      onset_pval = onset_pval,
                      intensity_pval = intensity_pval,
                      #lat_pval = lat_pval,
                      percent_data_used = percent_data_used,
                      R2 = R2,
                      residual_moran = residual_moran,
                      residual_moran_pval = residual_moran_pval,
                      onset_moran = onset_moran,
                      onset_moran_pval = onset_moran_pval,
                      plant_moran = plant_moran,
                      plant_moran_pval = plant_moran_pval,
                      highest_predictor_correlation = highest_predictor_correlation,
                      prediction_results_elimlocation = prediction_results_elimlocation
                      )
  }

  return(output_list)
}

# run one set of spatial sampling/predictor set
model_output <- run_OLS(full_data = cell_sf_tidy, 
                        predictors = c("onset", "intensity",
                          "lat", "lon", # for spatial effects
                          "year_index" # for time effects
                          #"onset:lat", "onset:lon", # interactions: for spatial effects
                          #"onset:year_factor", # interactions: for time effects
                          #"onset:intensity" # interactions: for intensity effects
                          ), 
                    y.var = "plant",
                    grid_size = 0.5, lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, 
                    plot_samples = TRUE, plot_model_evals = TRUE, 
                    year_oi = 2012, do_elim_year = FALSE)

print(model_output)


```


## model selection

```{r}

stepwise_model_selection <- function(max_variables, y.var, predictor_pool, data) {
  
  formula.string <- paste(y.var, paste(predictor_pool, collapse = " + "), sep = " ~ ")
  f <- as.formula(formula.string)
    
  step_result <- leaps::regsubsets(f, 
                                   data=data, 
                                    nbest=1, # number of subsets of each size to record
                                    nvmax=max_variables, # maximum size of subsets to examine
                                    force.in = c(1,2) # make sure onset and intensity are in all models
                                    )
  step_result_summary <- summary(step_result)
  kept_predictors <- step_result_summary$which
  
  #print(kept_predictors)
  
  # get the chosen predictors for the max number of variables; get rid of 2 index for onset and intensity
  final_predictors <- kept_predictors[max_variables - 2,] 
  final_predictors <- names(final_predictors[final_predictors])
  
  return(final_predictors)
}


# to store data for best predictors for each grid offset
predictors_for_offsets <- c()


for (lat_offset in seq(0, 1.5, by = 0.25)) { # 0 to 1.5
      for (lon_offset in seq(0, 1.5, by = 0.25)) { # 0 to 1.5
  
  grid_size = 0.75
  agg_scheme = FALSE

  # select the data according to offset
  # get sampled data
  sampled_data <- get_sampled_data(full_data = cell_sf_tidy, grid_size = grid_size, 
                                   lat_offset = lat_offset, lon_offset = lon_offset, agg_scheme = agg_scheme, 
                                   plot_samples = FALSE, year_oi = 2008)      
        
  # get the best predictors
  chosen_predictors <- stepwise_model_selection(max_variables = 6,
                           y.var = "plant",
                           predictor_pool <- c("onset", "intensity", # these must be included
                                                "year_index", "lat", "lon", "region", 
                                                "onset:intensity", "onset:lat", "onset:year_index", "onset:region"),
                           data = sampled_data
                      )

  predictors_for_offsets <- c(predictors_for_offsets, chosen_predictors)

  }
}

# list the nubmer of times each predictor shows up
print(sort(table(predictors_for_offsets)))
```

## functions to evaluate different sampling strategies and predictors

```{r}

# test different grid sizes and aggregation strategies. don't do any offset

do_elim_year = TRUE # TOGGLE TRUE IF USE YEAR AS TREND, FALSE IF USE YEAR AS FIXED EFFECT

results <- data.frame()

for (grid_size in c(0.75)) { # 0.25 to 1.75, seq(0.75, 1.25, 0.25)
  for (agg_scheme in c(FALSE)) {
    for (lat_offset in seq(0, 1.5, by = 0.25)) { # 0 to 1.5
      for (lon_offset in seq(0, 1.5, by = 0.25)) { # 0 to 1.5
        
        model_output <- run_OLS(full_data = cell_sf_tidy, 
                              predictors = c("onset", "intensity",
                                "region", "lat", "lon", # for spatial effects: lat, lon, region, Muni_code
                                "year_index" # for time effects
                                #"onset:intensity" # interactions: for intensity effects
                                ), 
                          y.var = "plant",
                          grid_size = grid_size, 
                          lat_offset = lat_offset, lon_offset = lon_offset, agg_scheme = agg_scheme, 
                          plot_samples = FALSE, plot_model_evals = TRUE, 
                          year_oi = 2007,
                          do_elim_year = do_elim_year)
        
        #if (agg_scheme) {agg_scheme_str <- "Agg"}
        #else {agg_scheme_str <- "NotAgg"}
        
        print(paste("grid size", grid_size))
        print(paste("agg scheme", agg_scheme))
    
        selected_output <- as.numeric(c(grid_size, agg_scheme, lat_offset, lon_offset,
                             model_output$onset_coef, model_output$intensity_coef, #model_output$lat_coef,
                             model_output$R2, model_output$percent_data_used, 
                             model_output$residual_moran_pval, model_output$onset_moran_pval, 
                             model_output$plant_moran_pval,
                             #mean(model_output$prediction_results_elimyear$RMSE, na.rm = TRUE), 
                             mean(model_output$prediction_results_elimlocation$RMSE, na.rm = TRUE)
                             ))
        
        if (do_elim_year) {
          selected_output <- c(selected_output, mean(model_output$prediction_results_elimyear$RMSE, na.rm = TRUE))
        }
        
        print(selected_output)
        results <- rbind(results, selected_output)
      }
    }
  }
}

if (do_elim_year) {
  names(results) <- c("grid_size", "agg_scheme", "lat_offset", "lon_offset",
                    "onset_coef", "intensity_coef", #"lat_coef",
                    "R2", "percent_used", "residual_moran_pval", "onset_moran_pval",
                    "plant_moran_pval",
                    "mean_RMSE_elimlocation", "mean_RMSE_elimyear")
}
if (!do_elim_year) {
  names(results) <- c("grid_size", "agg_scheme", "lat_offset", "lon_offset",
                    "onset_coef", "intensity_coef", #"lat_coef",
                    "R2", "percent_used", "residual_moran_pval", "onset_moran_pval",
                    "plant_moran_pval",
                    "mean_RMSE_elimlocation")
}

results$agg_scheme <- as.factor(results$agg_scheme)

# SAVED RESULTS
saveRDS(results, "spatial_sampling_results.rds")

# calculate mean and sd for each grid size x agg scheme, for different grid offsets
results_summary <- results %>%
                        group_by(grid_size, agg_scheme) %>%
                        summarize(
                          onset_coef_mean = mean(onset_coef),
                          onset_coef_sd = sd(onset_coef),
                          intensity_coef_mean = mean(intensity_coef),
                          intensity_coef_sd = sd(intensity_coef),
                          #lat_coef_mean = mean(lat_coef),
                          #lat_coef_sd = sd(lat_coef),
                          R2_mean = mean(R2),
                          R2_sd = sd(R2),
                          percent_used_mean = mean(percent_used),
                          percent_used_sd = sd(percent_used),
                          residual_moran_pval_mean = mean(residual_moran_pval),
                          residual_moran_pval_sd = sd(residual_moran_pval),
                          onset_moran_pval_mean = mean(onset_moran_pval),
                          onset_moran_pval_sd = sd(onset_moran_pval),
                          plant_moran_pval_mean = mean(plant_moran_pval),
                          plant_moran_pval_sd = sd(plant_moran_pval),
                          #RMSE_elimyear_mean = mean(mean_RMSE_elimyear), # TURN OFF IF USE YEAR AS FACTOR
                          #RMSE_elimyear_sd = sd(mean_RMSE_elimyear), # TURN OFF IF USE YEAR AS FACTOR
                          RMSE_elimlocation_mean = mean(mean_RMSE_elimlocation),
                          RMSE_elimlocation_sd = sd(mean_RMSE_elimlocation)
                        )

if (do_elim_year) {
  elim_year_summary <- results %>%
    group_by(grid_size, agg_scheme) %>%
    summarize(
      RMSE_elimyear_mean = mean(mean_RMSE_elimyear),
      RMSE_elimyear_sd = sd(mean_RMSE_elimyear) 
    )
  
  results_summary <- cbind(results_summary, elim_year_summary)
}

# compare grid sizes and aggregation schemes

plot_results <- function(data, x_data, y_data, x_label, y_label, col_data) {
  ggplot(data, aes(x = x_data, y = y_data, col = col_data)) +
    geom_line() +
    ggtitle(y_label) +
    xlab(x_label) +
    ylab(y_label)+
    labs(col = "Aggregation scheme") +
    theme_bw()
}

plot_results_summary <- function(data, x_data, y_data, y_sd, x_label, y_label, col_data) {
  ggplot(data, aes(x = x_data, y = y_data, col = col_data)) +
    geom_line() +
    geom_errorbar(aes(ymin=y_data-y_sd, ymax=y_data+y_sd), position=position_dodge(0.05)) +
    ggtitle(y_label) +
    xlab(x_label) +
    ylab(y_label)+
    labs(col = "Aggregation scheme") +
    theme_bw()
}

# plot results, summarizing for different grid offsets
plot_results_summary(data = results_summary, 
                     x_data = results_summary$grid_size, y_data = results_summary$onset_coef_mean,
                     y_sd = results_summary$onset_coef_sd,
                    x_label = "grid_size", y_label = "onset coefficient", 
                    col_data = results_summary$agg_scheme)

plot_results_summary(data = results_summary, 
                     x_data = results_summary$grid_size, y_data = results_summary$intensity_coef_mean,
                     y_sd = results_summary$intensity_coef_sd,
                    x_label = "grid_size", y_label = "intensity coefficient", 
                    col_data = results_summary$agg_scheme)

plot_results_summary(data = results_summary, 
                     x_data = results_summary$grid_size, y_data = results_summary$R2_mean,
                     y_sd = results_summary$R2_sd,
                    x_label = "grid_size", y_label = "R2", 
                    col_data = results_summary$agg_scheme)

plot_results_summary(data = results_summary, 
                     x_data = results_summary$grid_size, y_data = results_summary$percent_used_mean,
                     y_sd = results_summary$percent_used_sd,
                    x_label = "grid_size", y_label = "percent used", 
                    col_data = results_summary$agg_scheme)

plot_results_summary(data = results_summary, 
                     x_data = results_summary$grid_size, y_data = results_summary$residual_moran_pval_mean,
                     y_sd = results_summary$residual_moran_pval_sd,
                    x_label = "grid_size", y_label = "residual moran's I p value", 
                    col_data = results_summary$agg_scheme)

plot_results_summary(data = results_summary, 
                     x_data = results_summary$grid_size, y_data = results_summary$onset_moran_pval_mean,
                     y_sd = results_summary$onset_moran_pval_sd,
                    x_label = "grid_size", y_label = "onset moran's I p value", 
                    col_data = results_summary$agg_scheme)

plot_results_summary(data = results_summary, 
                     x_data = results_summary$grid_size, y_data = results_summary$plant_moran_pval_mean,
                     y_sd = results_summary$plant_moran_pval_sd,
                    x_label = "grid_size", y_label = "plant moran's I p value", 
                    col_data = results_summary$agg_scheme)

plot_results_summary(data = results_summary, 
                     x_data = results_summary$grid_size, y_data = results_summary$RMSE_elimlocation_mean,
                     y_sd = results_summary$RMSE_elimlocation_sd,
                    x_label = "grid_size", y_label = "RMSE from eliminating location", 
                    col_data = results_summary$agg_scheme)

if (do_elim_year) {
  plot_results_summary(data = results_summary, 
                       x_data = results_summary$grid_size, y_data = results_summary$RMSE_elimyear_mean,
                       y_sd = results_summary$RMSE_elimyear_sd,
                      x_label = "grid_size", y_label = "RMSE from eliminating year", 
                      col_data = results_summary$agg_scheme)
}

```